### PR TITLE
Rename `terms.json` to `terms.jsonc`

### PR DESCRIPTION
**Pull request by parkerbxyz**
Comments are not permitted in JSON. This adds support for inline comments by renaming `terms.json` to `terms.jsonc`. [JSONC](https://github.com/microsoft/node-jsonc-parser) is JSON with JavaScript style comments. This will resolve GitHub showing these comments as invalid JSON.

**Before:**

Screen Shot 2022-05-03 at 11 57 47 AM

**After:**

Screen Shot 2022-05-03 at 11 57 28 AM

### CODE REVIEW

**Review by sapegin — APPROVED** [review]
Thanks!

**Comment by parkerbxyz** [comment]
I noticed the conflict preventing you from merging this. It’s fixed now. 🙂

**Comment by sapegin** [comment]
Merged!

**Pull request merged**
